/* 
 * This file was automatically generated by generate_templates.py 
 * as one of mros2 features. You do not need to modify this. 
 */
#include "std_msgs/msg/string.hpp"


template mros2::Publisher mros2::Node::create_publisher<std_msgs::msg::String>(const std::string& topic_name, const mros2::QoSProfile& qos);
template void mros2::Publisher::publish(std_msgs::msg::String &msg);



template mros2::Subscriber mros2::Node::create_subscription(const std::string& topic_name, const mros2::QoSProfile& qos, void (*fp)(std_msgs::msg::String*));
template void mros2::Subscriber::callback_handler<std_msgs::msg::String>(void *callee, const rtps::ReaderCacheChange &cacheChange);
