/* 
 * This file was automatically generated by generate_templates.py 
 * as one of mros2 features. You do not need to modify this. 
 */
 
{%- for includeFile in includeFiles %}
{{includeFile}}
{%- endfor %}

{% for pubMsgType in pubMsgTypes %}
template mros2::Publisher mros2::Node::create_publisher<{{pubMsgType}}>(const std::string& topic_name, const mros2::QoSProfile& qos);
template void mros2::Publisher::publish({{pubMsgType}} &msg);
{% endfor %}

{% for subMsgType in subMsgTypes %}
template mros2::Subscriber mros2::Node::create_subscription(const std::string& topic_name, const mros2::QoSProfile& qos, void (*fp)({{subMsgType}}*));
template void mros2::Subscriber::callback_handler<{{subMsgType}}>(void *callee, const rtps::ReaderCacheChange &cacheChange);
{% endfor %}